name: fconsole
description: An overlay console log list like v-console.
version: 2.6.2
homepage: https://github.com/fluttercandies/fconsole

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^9.1.2
  intl: any
  tapped: ^2.0.0
  animations: ^2.0.8
  left_scroll_actions: ^2.1.2
  share_plus: ^7.2.2
  json_view: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
